### ISSUE TITLE
IMPORTANT: Please contact MoneyMoney developer before using OAuth in your own extension.

### ISSUE THREAD

**Issue by miracle2k** [diederich/moneymoney-monzo#3]
This is what it says in the source code. Why is that?

**Comment by diederich** [comment]
IIRC because it needs some code in the MoneyMoney app itself, like whitelisting, ...

@miracle2k I haven't checked where this is, but I guess it must be either from a template I copied, or @mrh-line added it when he helped me finish it.

Generally speaking, if you're interested in developing extension for MoneyMoney, check out https://moneymoney-app.com/extensions/.

**Comment by miracle2k** [comment]
Ok thanks!

AFAICT the extension documentation does not mention oAuth yet - I found this particular extension searching for how oAuth could be done. It's obviously something new, and reading this I thought I might encounter issues, but let's see.

**Comment by diederich** [comment]
I see, that makes sense, thanks for clarifying.

I think what I did, was to get the plugin working without the oauth parts (manual auth and fill in the token) and then asked @mrh-line for help - which turned out great :-)
